version: '3'
services:
  harvest-api:
    image: harvest-api:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 15050:80
    environment:
      - "CFG_FILE=config/env.cfg"
  mariadb:
    image: mariadb:10.1.23
    environment:
      - "MYSQL_DATABASE=harvest_local"
      - "MYSQL_ROOT_PASSWORD=farmingROBOT2018"
      - "MYSQL_USER=root"
    ports:
      - 3333:3306
