CREATE TABLE plants (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(45) DEFAULT NULL, bank VARCHAR(45) DEFAULT NULL, days INT(11) DEFAULT 0);
CREATE TABLE status (id BIGINT AUTO_INCREMENT PRIMARY KEY, plant_id BIGINT UNSIGNED NOT NULL, water INT DEFAULT 0, humidity INT DEFAULT 0, heat INT DEFAULT 0);
